export const studentsData = [
  {
    student_id: 1,
    name: "John Doe",
    disability: false,
    gender: "male",
    preferences: [2, 3, 4, 1, 5], // Company IDs in order of preference
  },
  {
    student_id: 2,
    name: "Jane Smith",
    disability: true,
    gender: "female",
    preferences: [4, 1, 5, 3, 2],
  },
  {
    student_id: 3,
    name: "Alex Johnson",
    disability: false,
    gender: "male",
    preferences: [1, 2, 3, 4, 5],
  },
  {
    student_id: 4,
    name: "Emily Brown",
    disability: true,
    gender: "female",
    preferences: [3, 2, 5, 1, 4],
  },
  {
    student_id: 5,
    name: "Michael Wilson",
    disability: false,
    gender: "male",
    preferences: [5, 1, 4, 3, 2],
  },
  {
    student_id: 6,
    name: "Emma Lee",
    disability: false,
    gender: "female",
    preferences: [1, 2, 3, 4, 5],
  },
  {
    student_id: 7,
    name: "William Garcia",
    disability: false,
    gender: "male",
    preferences: [5, 4, 3, 2, 1],
  },
  {
    student_id: 8,
    name: "Olivia Martinez",
    disability: true,
    gender: "female",
    preferences: [2, 3, 4, 1, 5],
  },
  {
    student_id: 9,
    name: "James Robinson",
    disability: false,
    gender: "male",
    preferences: [3, 1, 5, 4, 2],
  },
  {
    student_id: 10,
    name: "Sophia Clark",
    disability: true,
    gender: "female",
    preferences: [4, 5, 3, 2, 1],
  },
  {
    student_id: 11,
    name: "Benjamin Lewis",
    disability: false,
    gender: "male",
    preferences: [2, 3, 1, 4, 5],
  },
  {
    student_id: 12,
    name: "Isabella Walker",
    disability: false,
    gender: "female",
    preferences: [3, 2, 4, 1, 5],
  },
  {
    student_id: 13,
    name: "Daniel Hall",
    disability: true,
    gender: "male",
    preferences: [5, 1, 2, 4, 3],
  },
  {
    student_id: 14,
    name: "Mia Young",
    disability: false,
    gender: "female",
    preferences: [1, 2, 3, 5, 4],
  },
  {
    student_id: 15,
    name: "Logan Hernandez",
    disability: true,
    gender: "male",
    preferences: [3, 4, 1, 5, 2],
  },
  {
    student_id: 16,
    name: "Amelia King",
    disability: false,
    gender: "female",
    preferences: [5, 4, 3, 2, 1],
  },
  {
    student_id: 17,
    name: "Michael Wright",
    disability: false,
    gender: "male",
    preferences: [1, 5, 2, 4, 3],
  },
  {
    student_id: 18,
    name: "Ella Scott",
    disability: true,
    gender: "female",
    preferences: [4, 3, 2, 1, 5],
  },
  {
    student_id: 19,
    name: "Alexander Green",
    disability: false,
    gender: "male",
    preferences: [2, 1, 5, 4, 3],
  },
  {
    student_id: 20,
    name: "Grace Adams",
    disability: true,
    gender: "female",
    preferences: [3, 4, 1, 2, 5],
  },
];
