export const studentsData = [
  {
    student_id: 1,
    name: "John Doe",
    disability: false,
    gender: "male",
    gpa: 2.7,
    preferences: [1, 2, 3, 4],
  },
  {
    student_id: 2,
    name: "David Williams",
    disability: false,
    gender: "male",
    gpa: 2.75,
    preferences: [1, 2, 3, 4],
  },
  {
    student_id: 3,
    name: "Sophie Wilson",
    disability: false,
    gender: "female",
    gpa: 3.5,
    preferences: [1, 3, 2, 4],
  },
  {
    student_id: 4,
    name: "Ava Rodriguez",
    disability: false,
    gender: "female",
    gpa: 2.8,
    preferences: [1, 2, 4, 3],
  },
  {
    student_id: 5,
    name: "Jameson Baker",
    disability: true,
    gender: "female",
    gpa: 4,
    preferences: [1, 3, 4, 2],
  },
  {
    student_id: 6,
    name: "Amelia Johnson",
    disability: true,
    gender: "female",
    gpa: 2.4,
    preferences: [1, 2, 3, 4],
  },
  {
    student_id: 7,
    name: "William Brown",
    disability: true,
    gender: "male",
    gpa: 3.8,
    preferences: [1, 2, 3, 4],
  },
  {
    student_id: 8,
    name: "Sophia Miller",
    disability: false,
    gender: "female",
    gpa: 2.7,
    preferences: [1, 2, 3, 4],
  },
  {
    student_id: 9,
    name: "Jane Smith",
    disability: true,
    gender: "female",
    gpa: 3.75,
    preferences: [2, 3, 1, 4],
  },
  {
    student_id: 10,
    name: "Emily Brown",
    disability: true,
    gender: "female",
    gpa: 3,
    preferences: [2, 4, 3, 1],
  },
  {
    student_id: 11,
    name: "James Wilson",
    disability: false,
    gender: "male",
    gpa: 3.6,
    preferences: [2, 4, 1, 3],
  },
  {
    student_id: 12,
    name: "Olivia Taylor",
    disability: true,
    gender: "female",
    gpa: 3.1,
    preferences: [2, 4, 1, 3],
  },
  {
    student_id: 13,
    name: "Michael Johnson",
    disability: false,
    gender: "male",
    gpa: 3.25,
    preferences: [3, 2, 4, 1],
  },
  {
    student_id: 14,
    name: "Ethan Anderson",
    disability: false,
    gender: "male",
    gpa: 3.9,
    preferences: [2, 3, 4, 1],
  },
];
